### ISSUE TITLE
IE Browser support

### ISSUE THREAD

**Issue by jasonkarns** [adrai/enum#18]
What's the expected level of IE support? The tests currently fail to load/run in IE8 and 9. The tests run in IE10 but they all fail (when attempting to instantiate an enum):

```
TypeError: Object doesn't support property or method '__defineGetter__'
```

**Comment by adrai** [comment]
I added your changes for ie... May you want to test it? just take the master and run gulp (this will generate the new needed dist files)

**Comment by jasonkarns** [comment]
The tests don't even run in IE8 or 9, and I strongly suspect this is due to babel (which doesn't support IE8/9 without some careful selection of transforms and shims. see [caveats](http://babeljs.io/docs/usage/caveats/))

And as a library, I don't think it's polite to force a shim on users for those features. My vote is to drop the babel compilation for now. Babel is great for applications, but for library authors, it just removes browser support choices from downstream consumers. As it stands now, I'm forced to use my fork of enum as the npm-published module simply doesn't work in IE 8 or 9.

![IE8](https://cloud.githubusercontent.com/assets/119972/6646157/a39c1e18-c998-11e4-9687-a254d15d5192.png)
![IE9](https://cloud.githubusercontent.com/assets/119972/6646156/a398c6d2-c998-11e4-9a95-ef8eee9ce8b2.png)

**Comment by adrai** [comment]
There is no  released version of enum that was build with babel...
So it's something else... Can you help?

**Comment by adrai** [comment]
Can you test from master as descrived before?

**Comment by jasonkarns** [comment]
The screenshots shown aren't of the released version, but of the
test/test.html page running from `master` (after a gulp build)

**Comment by adrai** [comment]
Hmmmm ok... then I need an IE...

**Comment by stoeffel** [comment]
The tests aren't build with babel and contain 'Object.defineProperty`. So if you open the test/test.html in IE8 it fails at https://github.com/adrai/enum/blob/master/test/enumTest.js#L399

**Comment by jasonkarns** [comment]
Are you sure that's it? I have the same test suite running on my fork (pre-babel) and the tests actually run. (They don't all pass, but they at least run)

**Comment by stoeffel** [comment]
Ou... just saw that it could be that the problem is, that the current test suite requires the es6 file from `../lib/enum` and not a build (babel) one (checkout https://github.com/adrai/enum/blob/master/test/enumTest.js#L3)

**Comment by jasonkarns** [comment]
test.html has a script reference to the babel build: https://github.com/adrai/enum/blob/master/test/test.html#L11

which defines Enum so the `require` call isn't invoked. (Otherwise it would bomb saying there's no such function as `require`)

**Comment by adrai** [comment]
@jasonkarns may you test again from master?

**Comment by adrai** [comment]
v2.0.1
