### ISSUE TITLE
performance issue

### ISSUE THREAD

**Issue by erossignon** [adrai/enum#21]
It looks like the code freezing stuff introduced in some recent has a negatif impact on performance.
We had to revert to a lighter/older implementation of Enum on our project 

https://github.com/node-opcua/node-opcua/blob/master/lib/misc/enum.js
https://github.com/node-opcua/node-opcua/blob/master/test/misc/test_enum.js

Our test shows a 50x performance increase:
```
  Test Enum
    √ should create flaggable enum from string array
    √ should create flaggable enum from flaggable map
    √ should create non-flaggable enum from non-flaggable map
    √ should access enum from enum item name
    √ EnumItem should function properly

  Benchmarking Enums
 CYCLE slowEnum op/s 1251.3981929889926
 CYCLE fastEnum op/s 137125.85574360698
 Fastest is fastEnum
 Speed Up : x 109
    √ should verify that our enums are faster than old enums (1084ms)
 CYCLE slowEnum op/s 624.8278866171509
 CYCLE fastEnum op/s 38325.48636183134
 Fastest is fastEnum
 Speed Up : x 61
    √ should verify that our enums are faster than old enums (1027ms)
 CYCLE slowEnum op/s 937.1482653018942
 CYCLE fastEnum op/s 75088.35966278995
 Fastest is fastEnum
 Speed Up : x 80
    √ should verify that our enums are faster than old enums (1046ms)
  8 passing (3s)
```

see https://github.com/node-opcua/node-opcua/pull/71

**Comment by adrai** [comment]
What if we would introduce a new option freeze so you can choose to freeze or not...?

**Comment by adrai** [comment]
Is someone needing this freeze feature???

**Comment by stoeffel** [comment]
With PR #22 freezing will be disabled by default.

**Comment by adrai** [comment]
+1

**Comment by adrai** [comment]
@erossignon ok for you?

**Comment by stoeffel** [comment]
btw. this [L232-L235](https://github.com/adrai/enum/blob/master/lib/enum.es6#L232-L235) is one reason why it is slow.

With defining getters and setters.
```js
[15:05:24] Running benchmark freez [/Users/stoeffel/enum/bench/freez.js]...
[15:05:29] freez x 329 ops/sec ±1.66% (90 runs sampled)
```

Without
```js
[15:07:40] Running benchmark freez [/Users/stoeffel/enum/bench/freez.js]...
[15:07:46] freez x 73,224 ops/sec ±2.09% (97 runs sampled)
```

**Comment by adrai** [comment]
I think we should do a new release...

**Comment by stoeffel** [comment]
:+1: on a new release. I'm afk until sunday though.
