### ISSUE TITLE
How to iterate  Enum Object 

### ISSUE THREAD

**Issue by abhaygarg12493** [adrai/enum#23]
This is Enum Object 

cameraType=new Enum({'HIKVISION':"HikVision", 'DAHUA':"Dahua", "FOSCAM":"Foscam"});
module.exports.cameraType=cameraType

And when we try to iterate 

 Object.keys(constant.cameraType).forEach(function(element, key, _array) {
                console.log("element is ",element);
                console.log("Value is  ",constant.cameraType.getValue(element));
   });

Then it output contain more variable then we intialize 

Output is 

element is  size
Value is   undefined
element is  indirection
Value is   undefined
element is  _options
Value is   undefined
element is  enums
Value is   undefined
element is  HIKVISION
Value is   HikVision
element is  DAHUA
Value is   Dahua
element is  FOSCAM
Value is   Foscam
element is  isFlaggable
Value is   undefined

**Comment by stoeffel** [comment]
You can do f.e:

```js
cameraType.enums.forEach(function(element) {
  console.log("element is ",element); // EnumItem
  console.log(element.key); // HIKVISION, DAHUA, FOSCAM
});
```

Checkout: http://requirebin.com/?gist=2505cede91e5f138c2bb

Did this help?

**Comment by abhaygarg12493** [comment]
Yes It helps 
Thanks a lot
