### ISSUE TITLE
Why are the "built" enum-X.js files npmignored?

### ISSUE THREAD

**Issue by juuxstar** [adrai/enum#25]
Most libraries distribute their packaged files with npm so that they can be served to the browser from the same source dir as the server's version.

As it is now, I have to use `npm install enum` and maintain one version for the server and maintain a separate dependency for the browser.  This is not browser friendly even though the library should work great between node and the browser.

So essentially, I'm asking to remove: https://github.com/adrai/enum/blob/master/.npmignore#L3

**Comment by stoeffel** [comment]
Removing this line is okay for me... @adrai any objections?

@juuxstar Will you make a PR?

**Comment by adrai** [comment]
Ok
