### ISSUE TITLE
Adding Method to Serialize Enum

### ISSUE THREAD

**Issue by Bluejay47** [adrai/enum#29]
Serializing 'enums' doesn't include the keys, just the values. 

I get this:
["BRANDS_INSPIRED","CRAFTS","DECOR","ELECTRONICS","FURNITURE","HOME_AUTOMATION","HOME_IMPROVEMENT","OUTDOORS","UPCYCLE","WEDDINGS","MISC"]

When I want this:
[{"key":"BRANDS_INSPIRED","value":"Brands Inspired"},{"key":"CRAFTS","value":"Crafts"},{"key":"DECOR","value":"Décor"},{"key":"ELECTRONICS","value":"Electronics"},{"key":"FURNITURE","value":"Furniture"},{"key":"HOME_AUTOMATION","value":"Home Automation"},{"key":"HOME_IMPROVEMENT","value":"Home Improvement"},{"key":"OUTDOORS","value":"Outdoors"},{"key":"UPCYCLE","value":"Upcycle"},{"key":"WEDDINGS","value":"Weddings"},{"key":"MISC","value":"Miscellaneous"}]

I added a short method to my local copy to make this a bit quicker since I do this a lot. Is there some better way to go about this?

Thanks,

Added method:

```
 /**
 * Returns an array of objects with key / value pairs for the elements of the enumeration.
 * @return {Array} Objects with key / value attributes
 */

  Enum.prototype.toTuples = function toTuples() {
        
        var elements = [];
        
        this.enums.forEach(function (element) {
            if (element.key) {
                elements.push({ 'key': element.key, 'value': element.value });
            } else {
                elements.push(element.value);
            }
        });
        
        return elements;

    };  
```

**Comment by adrai** [comment]
Isn't this function just returning the same as this.enums?

**Comment by Bluejay47** [comment]
Possibly I am doing something stupid, but when I try to serialize or stringify enums I just get the values -- not the keys.

Just this...

["BRANDS_INSPIRED","CRAFTS","DECOR","ELECTRONICS","FURNITURE","HOME_AUTOMATION","HOME_IMPROVEMENT","OUTDOORS","UPCYCLE","WEDDINGS","MISC"]

**Comment by adrai** [comment]
would this be ok?

```javascript
var myEnum = new Enum({'None': 0, 'Black':1, 'Red': 2, 'Red2': 3, 'Green': 4, 'Blue': 5});
myEnum.toJSON(); // returns {'None': 0, 'Black':1, 'Red': 2, 'Red2': 3, 'Green': 4, 'Blue': 5}
JSON.stringify(myEnum); // returns '{"None":0,"Black":1,"Red":2,"Red2":3,"Green":4,"Blue":5}'
```

**Comment by TooTallNate** [comment]
:+1: for `toJSON()`

**Comment by adrai** [comment]
v2.2.0

**Comment by Bluejay47** [comment]
Works for me :)  

Thanks.

**Comment by Bluejay47** [comment]
Actually if I might make one minor suggestion, it might be best to separate out the individual enum values as objects and make it an array. As it is the enums are properties of a single object and that makes it more difficult to enumerate the enumerated values.
