### ISSUE TITLE
Extend Enums before freezing?

### ISSUE THREAD

**Issue by vasumahesh1** [adrai/enum#30]
Hi,

Possible to Extend an Enum before freezing it?

I have a use case:
I have a global npm module that has a set of Enums and is included in an application which has its own set of enums, can I somehow merge them together?

Also by merging as in the global module's Enum is already instantiated...

I wrote a piece of code that does the job, but It wont be as per the requirements i.e. I haven't take aspects like frozen into account yet.

**Comment by adrai** [comment]
Can't you create a new Enum containing all values?

**Comment by vasumahesh1** [comment]
No actually, when I require the global module the Enum comes as instantiated ... I didn't want the localized module to create the Enum rather just extend it with the enum coming from global module...

this is because the sequence values will get altered, and some of the code in the global module is using the Enum (without extension) and localized module is using the Enum (with extension) 

If i create a new enum then the EnumItem sent by the Global module will have different values corresponding to the ones in the localized module

**Comment by vasumahesh1** [comment]
Like for eg:

```js
var myModule = require('myModule');
var CODES = myModule.CODES; // Already comes as Enum, Say ['SUCCESS': 1, 'FAIL': 2]

// Later Ahead
CODES.extend(['PENDING']); // Becomes ['SUCCESS': 1, 'FAIL': 2, 'PENDING': 4]
```

If you could suggest another alternative would be great.. Another way I see is to get only the Array values from the global module and try to make an Enum and Pass it back into the global module.

**Comment by adrai** [comment]
Can you try to do a PR?

**Comment by vasumahesh1** [comment]
Yeah sure thing!

**Comment by adrai** [comment]
v2.3.0
