### ISSUE TITLE
Best way to assert an enum item was passed

### ISSUE THREAD

**Issue by silverbp** [adrai/enum#34]
Lets say you wanted to take an enum item as a parameter to a function.

What's the best way to assert that what was passed is an enum item. I've done some hacks doing index of with the array of values or something similar, but it seems there should be an easier way to do this.

**Comment by adrai** [comment]
You're right!
There is no nice function for this...
Can you do a PR?

**Comment by agutierrezcu** [comment]
@silverbp I've performed pull request #37 which changes i think could help you to check whether an  EnumItem object is passed in to a function as parameter.

**Comment by leite08** [comment]
From what I understand from the PR it is supposed to check if an `EnumItem` is part of a given `Enum` instance, right?

I got here looking for a way to do a `x instanceof EnumItem`.

This is not possible at this time since `EnumItem` is not exported from the module, right?

**Comment by adrai** [comment]
If there is a need for "x instanceof EnumItem" please try a PR.
