### ISSUE TITLE
EnumItem#has returns true falsely.

### ISSUE THREAD

**Issue by gt-c** [adrai/enum#44]
When EnumItem#has is called with a string, it is checked if EnumItem#key (string) contains the string provided to '.has'. I have reached an issue where one enum is a substring of another, e.g. HELL, HELLO. When the EnumItem contains HELLO, and I attempt to use `<EnumItem>.has('HELL")`, it will incorrectly return true. Please tell me if this is intended or anything, for now I will just have to rename the enums.

Sorry for any inproper usage of terms in advance, I'm relatively new to this dependency (and enums in general).

**Comment by adrai** [comment]
I think, it’s sort of intended, but I don’t remember why... 😕

**Comment by adrai** [comment]
This thread has been closed since there has not been any recent activity. Please reopen if still needed.
