### ISSUE TITLE
Consider using Pagic to build the website?

### ISSUE THREAD

**Issue by xcatliu** [adrai/enum#47]
[Pagic](https://pagic.org) is a static site generator powered by Deno + React

Here are some demos:

- [pagic.org](https://pagic.org)
- [Deno X ranking](https://yoshixmk.github.io/deno-x-ranking/)
- [TypeScript 入门教程](https://ts.xcatliu.com/)

If it is possible to use pagic to build the website, I would like to create the pull-request

**Comment by adrai** [comment]
Which website?

**Comment by AlexZhong22c** [comment]
> Which website?

He means that he would help to build a homepage of this library with Pagic, if got permission.  @adrai

**Comment by adrai** [comment]
I don't think this tiny module deserves its own website.
In terms of content, it's just what is in the README.md. 
🤷‍♂️

**Comment by AlexZhong22c** [comment]
Aha. As far as i am concerned, this lib could go further and get more stars with better prettifying or beautifying.

In terms of popularity, may be, getting translated into others languages with READMEs, would be better than building an homepage.

For example, me, as a guy known little about English, it's hard to search into it or decide wether to use it, with some many 'English' describing the detail features.

@adrai 

Also you can close the issue, and i though this as a promotion of (xcatliu) his production. 😄
