### ISSUE TITLE
isinstance check?

### ISSUE THREAD

**Issue by velis74** [adrai/enum#49]
I'm trying to use this in Vue props. But Vue complains that the Enum is not a constructor / class.

Indeed, if I try do to a `MyEnum.ENUM instanceof MyEnum`, I will get a TypeError saying that "....._default is not a function".

What would be the proper way of making the instance check?

**Comment by adrai** [comment]
Can you create a reproducible example?

**Comment by velis74** [comment]
```
const DisplayMode = new Enum({
  SUPPRESS: 1,
  HIDDEN: 5,
  INVISIBLE: 8,
  FULL: 10,
}, { freeze: true });

console.log(DisplayMode.SUPPRESS instanceof DisplayMode);
```
Edit: remove the unnecessary comments

**Comment by adrai** [comment]
Why do you use instanceof at all?
instanceof is only to check if it is an enum.
You may use isDefined instead: https://codesandbox.io/s/goofy-glitter-vwhdt?file=/src/index.js:233-271

**Comment by velis74** [comment]
I know. That's what I do now.
My Vue prop declaration is currently:

`displayComponent: { type: Object, required: true, validator(value) { return ComponentDisplay.isDefined(value); } },`

It would be much better if it were:

`displayComponent: { type: ComponentDisplay, required: true },`

**Comment by adrai** [comment]
If you know how this could be done feel free to provide a PR

**Comment by velis74** [comment]
I do not. I was just asking if you designed anything like that. 

Thanks for your super-fast response, though. And for this great package. Was looking for a while now how to better solve my Enums. This package provides just about everything I ever wished for.
