### ISSUE TITLE
Failed to import Enum

### ISSUE THREAD

**Issue by yjf0824** [adrai/enum#50]
import Enum from 'enum'
 Could not find a declaration file for module 'enum'. '/Users/jerry/opt/test/project/node_modules/enum/cjs/enum.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/enum` if it exists or add a new declaration (.d.ts) file containing `declare module 'enum';`

1 import Enum from 'enum'

**Comment by adrai** [comment]
This is not a TypeScript library.

For TypeScript have a look at: https://www.typescriptlang.org/docs/handbook/enums.html
