### ISSUE TITLE
Feature request: case (in)sensitivity

### ISSUE THREAD

**Issue by jasonkarns** [adrai/enum#6]
Would you be receptive to adding case insensitivity as an option?

I'm thinking something along the lines of:

``` javascript
var myEnum = new Enum(['One', 'Two'], { caseSensitive: false }); // caseSensitive defaults to true

myEnum.get('one'); // => myEnum.One
myEnum.get('ONE'); // => myEnum.One
myEnum.Two.is('two'); // => true
```

I would expect that the canonical casing is taken from the constructor argument. So the property accessor (`One` and `Two` above) is only available as defined during instantiation. But the `get`, `is`, and `has` lookup methods would be case insensitive (or sensitive) as defined by the provided option (defaulting to sensitive).

**Comment by adrai** [comment]
Why not? Feel free to make a pull request...
Hint: I would name the option "ignoreCase"
