### ISSUE TITLE
Interested in "ref" type support?

### ISSUE THREAD

**Issue by TooTallNate** [adrai/enum#7]
Hey there! I'm not sure if you are aware of [`ref`](https://github.com/TooTallNate/ref) and its counterpart, [`node-ffi`](https://github.com/node-ffi/node-ffi), but I was checking out this module, and thinking it would be really cool to have this `Enum` module be a supported "Type" for use in FFI'd C functions! There's already [`ref-array`](https://github.com/TooTallNate/ref-array) for C arrays, and [`ref-struct`](https://github.com/TooTallNate/ref-struct) for C-compatible structs in Buffers. Enum is a natural fit!

Do do this, we'd have to have to add a few properties to the Enum class instance, to make it a compatible ["ref type"](https://github.com/TooTallNate/ref#the-type-interface).

If you're interested in this, I can probably whip up a PR pretty quickly! Cheers :beers:

**Comment by adrai** [comment]
Unfortunately I'm not aware of ref (but sounds interesting).
For sure, feel free to do a PR...
