### ISSUE TITLE
`valueOf()` should return `this.value`, not `this.key`?

### ISSUE THREAD

**Issue by TooTallNate** [adrai/enum#8]
How come `valueOf()` returns the key, instead of the value? If it was `this.value`, we'd be able to use JavaScript `|`, similar to the way the Enum separator syntax works:

``` js
var myEnum = new Enum(['A', 'B', 'C']);

myEnum.A | myEnum.B;
// 3

myEnum.get('A | B');
// { key: 'A | B', value: 3 }

myEnum.get('A | B').value;
// 3
```

Thoughts?

**Comment by adrai** [comment]
I think you're right... Include it in your PR... if you want to...

**Comment by TooTallNate** [comment]
PR sent in #10!

**Comment by adrai** [comment]
When you confirm everything is ok for you, I will publish v1.0.0 to npm

**Comment by TooTallNate** [comment]
Sweet! :+1: all tests are passing. publish away!

**Comment by adrai** [comment]
done

**Comment by TooTallNate** [comment]
Thanks!
